### ISSUE TITLE
shareable link to each event card

### ISSUE THREAD

**Issue by appukurian** [tinkerhub/saturday-hack-night#23]
previous events and projects listed on the [events page](https://hacknight.tinkerhub.org/events), get a shareable link to each card

**Comment by sreehari2003** [comment]
@DarkPhoenix2704  we could open a model when the user presses the more info button on the card which shows the info of the event.
 we could create a shareable link by creating a query on URL onPress.

EG := "https://hacknight.tinkerhub.org/events?name=discord"

what do you think ?
