### ISSUE TITLE
ui issue on profile modal

### ISSUE THREAD

**Issue by sreehari2003** [tinkerhub/saturday-hack-night#68]
### Todo
* add the chakra react select library for  react select which give the chkara ui theme feel

![image](https://github.com/tinkerhub/saturday-hack-night/assets/66205494/55c3e49d-e4e6-48ed-9c87-bde364af7a22)

**Comment by Morning1139Angel** [comment]
hi ! I am currently just a new beginner ... but if ud allow me to Id love to give this a try !
